### ISSUE TITLE
not injecting when using vandium

### ISSUE THREAD

**Issue by vanerleo** [arabold/serverless-sentry-plugin#4] opened 2016-07-19 00:13 UTC
Started using vandium, sentry no longer injecting

executed :
`
sls function deploy -t -s dev
`
checked _tmp\, code did not get modified

sample code :

```
'use strict';
const vandium = require('vandium');
const db = require('./db.js');
const factoryCommonData = require('./factory-common-data.js');

var _connection = {};

vandium.after(function () {
  return _connection.end();
});


module.exports.handler = vandium(main);

/***************MAIN IMPLEMENTATION********************/
 function main(event){    

  return db.GetConnection()
    .then(function (connection) {
      _connection = connection;

      return factoryCommonData.Countries(_connection);
    })
}
```

**Comment by vanerleo** [comment] 2016-07-19 08:48
on further inspection, i can see file `_serverless_handler.js` gets generated and included,
how does it get called?

**Comment by arabold** [comment] 2016-07-20 15:47
Thanks for your bug report. I haven't spend any time with Vandium yet so I'll have to look into it first. Vandium uses a different runtime name (`nodejs4.3-vandium`) which might be the reason for the issue you see.

The `_serverless_handler.js` is created by serverless for the `node` and `nodejs4.3` runtimes and the `serverless-sentry-plugin` hooks into that same file, appending its own code at the end. AWS Lambda then invokes `_serverless_handler.js`. 

I _assume_ the issue is somewhere in that file or whatever Vandium uses during scaffolding. I'll have to take a deeper look to figure out what they do differently and if there's an easy solution for it.

**Comment by arabold** [comment] 2017-07-05 22:37
A new version 1.0.0-rc.1 of this plugin that works with Serverless 1.x is available now. I'm going to close this issue.

**Closed by arabold** 2017-07-05 22:37 UTC
Labels: sls0.5
